- name: download ca
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: /ca/ca.pem
    dest: "{{ role_path }}/files/ca.pem"
    mode: get

- name: download ca-key.pem
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: /ca/ca-key.pem
    dest: "{{ role_path }}/files/ca-key.pem"
    mode: get

- name: download ca-config
  amazon.aws.aws_s3:
    bucket: "{{ bucket }}"
    object: /ca/ca-config.json
    dest: "{{ role_path }}/files/ca-config.json"
    mode: get

- name: kube worker hostname
  shell: curl http://169.254.169.254/latest/meta-data/local-hostname
  register: worker_host

- set_fact: 
    worker_host={{ worker_host.stdout }}

- name: kube worker ip address
  shell: curl http://169.254.169.254/latest/meta-data/local-ipv4
  register: worker_ip

- set_fact: 
    worker_ip={{ worker_ip.stdout }}

- name: kube worker loadbalancer
  shell: aws elbv2 describe-load-balancers --region us-east-1 --name kubeworker-int-lb | jq -r '.LoadBalancers[].DNSName'
  register: worker_lb

- set_fact: 
    worker_lb={{ worker_lb.stdout }}

- name: kube master loadbalancer
  shell: aws elbv2 describe-load-balancers --region us-east-1 --name kubemaster-int-lb | jq -r '.LoadBalancers[].DNSName'
  register: master_lb

- set_fact: 
    master_lb={{ master_lb.stdout }}

- name: generate kube worker csr
  template:
    src: "{{ role_path }}/templates/worker-csr.json.j2"
    dest: "{{ role_path }}/files/{{worker_host}}-csr.json"

- name: generate certificate for worker nodes
  shell: "cfssl gencert -ca={{ role_path }}/files/ca.pem -ca-key={{ role_path }}/files/ca-key.pem -config={{ role_path }}/files/ca-config.json -hostname={{ worker_host }},{{  worker_ip }},{{ worker_lb }} -profile=kubernetes {{ role_path }}/files/{{ worker_host }}-csr.json | cfssljson -bare {{ role_path }}/files/{{ worker_host}}"

- name: generate kube config for the workers
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way --certificate-authority={{ role_path }}/files/ca.pem --embed-certs=true --server=https://{{ master_lb }}:6443 --kubeconfig={{ role_path }}/files/{{ worker_host}}.kubeconfig
    kubectl config set-credentials system:node:{{ worker_host }} --client-certificate={{ role_path }}/files/{{ worker_host}}.pem --client-key={{ role_path }}/files/{{ worker_host}}-key.pem --embed-certs=true --kubeconfig={{ role_path }}/files/{{ worker_host}}.kubeconfig
    kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:node:{{ worker_host }} --kubeconfig={{ role_path }}/files/{{ worker_host}}.kubeconfig
    kubectl config use-context default --kubeconfig={{ role_path }}/files/{{ worker_host}}.kubeconfig

- name: generate kube proxy config 
  shell: | 
    kubectl config set-cluster kubernetes-the-hard-way --certificate-authority={{ role_path }}/files/ca.pem --embed-certs=true --server=https://{{ master_lb }}:6443 --kubeconfig={{ role_path }}/files/kube-proxy.kubeconfig
    kubectl config set-credentials system:kube-proxy --client-certificate={{ role_path }}/files/kube-proxy.pem --client-key={{ role_path }}/files/kube-proxy-key.pem --embed-certs=true --kubeconfig={{ role_path }}/files/kube-proxy.kubeconfig
    kubectl config set-context default --cluster=kubernetes-the-hard-way --user=system:kube-proxy --kubeconfig={{ role_path }}/files/kube-proxy.kubeconfig
    kubectl config use-context default --kubeconfig={{ role_path }}/files/kube-proxy.kubeconfig