- name: kube worker hostname
  shell: curl http://169.254.169.254/latest/meta-data/local-hostname
  register: worker_host

- name: kube worker ip address
  shell: curl http://169.254.169.254/latest/meta-data/local-ipv4
  register: worker_ip

- name: kube worker loadbalancer
  shell: aws elbv2 describe-load-balancers --region us-east-1 --name kubeworker-int-lb | jq -r '.LoadBalancers[].DNSName'
  register: worker_lb

- name: kube master loadbalancer
  shell: aws elbv2 describe-load-balancers --region us-east-1 --name kubemaster-int-lb | jq -r '.LoadBalancers[].DNSName'
  register: master_lb

- name: POD_CIDR create
  shell: cat /tmp/POD_CIDR
  register: POD_CIDR

- set_fact: 
    worker_host: "{{ worker_host.stdout }}"
    worker_ip: "{{ worker_ip.stdout }}"
    worker_lb: "{{ worker_lb.stdout }}"
    master_lb: "{{ master_lb.stdout }}"
    POD_CIDR: "{{ POD_CIDR.stdout }}"